param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

function Get-UnityGuid {
    param([string]$InputText)
    $md5 = [System.Security.Cryptography.MD5]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($InputText)
    $hash = ($md5.ComputeHash($bytes) | ForEach-Object { $_.ToString('x2') }) -join ''
    return ('{0}-{1}-{2}-{3}-{4}' -f $hash.Substring(0,8), $hash.Substring(8,4), $hash.Substring(12,4), $hash.Substring(16,4), $hash.Substring(20,12)).ToUpper()
}

function Parse-RspFile {
    param([string]$Path)
    $references = @()
    $sources = @()
    $analyzers = @()
    $defines = @()
    $additionalFiles = @()
    $langVersion = '9.0'

    foreach ($line in Get-Content $Path) {
        $line = $line.Trim()
        if ($line -match '^-r:"(.+)"$') { $references += $Matches[1] }
        elseif ($line -match '^-define:(.+)$') { $defines += $Matches[1] }
        elseif ($line -match '^-analyzer:"(.+)"$') { $analyzers += $Matches[1] }
        elseif ($line -match '^-langversion:(.+)$') { $langVersion = $Matches[1] }
        elseif ($line -match '^/additionalfile:"(.+)"$') { $additionalFiles += $Matches[1] }
        elseif ($line -match '^"(.+)"$' -and $line -like '*.cs*') { $sources += $Matches[1] }
    }

    return [pscustomobject]@{
        References = $references
        Sources = $sources
        Analyzers = $analyzers
        Defines = ($defines | Select-Object -Unique)
        AdditionalFiles = $additionalFiles
        LangVersion = $langVersion
    }
}

function New-UnityCsproj {
    param(
        [string]$AssemblyName,
        [string]$OutputPath,
        [object]$Rsp,
        [string[]]$ProjectReferences = @()
    )

    $projectGuid = Get-UnityGuid "$AssemblyName`salt"
    $projectType = if ($AssemblyName -like '*Editor*') { '5:5' } else { '1:1' }
    $defineConstants = ($Rsp.Defines -join ';')

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('<Project>')
    [void]$sb.AppendLine('  <!-- Generated by Tools/GenerateUnityProjects.ps1. Prefer Unity: Edit > Preferences > External Tools > Regenerate project files -->')
    [void]$sb.AppendLine('  <PropertyGroup>')
    [void]$sb.AppendLine('    <BaseIntermediateOutputPath>Temp\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>')
    [void]$sb.AppendLine('    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>')
    [void]$sb.AppendLine('    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>')
    [void]$sb.AppendLine('    <UseCommonOutputDirectory>true</UseCommonOutputDirectory>')
    [void]$sb.AppendLine("    <OutputPath>$OutputPath</OutputPath>")
    [void]$sb.AppendLine('  </PropertyGroup>')
    [void]$sb.AppendLine('  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />')
    [void]$sb.AppendLine('  <ItemGroup>')
    [void]$sb.AppendLine('    <Capability Include="Unity" />')
    [void]$sb.AppendLine('  </ItemGroup>')
    [void]$sb.AppendLine('  <PropertyGroup>')
    [void]$sb.AppendLine('    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>')
    [void]$sb.AppendLine('    <EnableDefaultItems>false</EnableDefaultItems>')
    [void]$sb.AppendLine("    <LangVersion>$($Rsp.LangVersion)</LangVersion>")
    [void]$sb.AppendLine('    <RootNamespace></RootNamespace>')
    [void]$sb.AppendLine('    <OutputType>Library</OutputType>')
    [void]$sb.AppendLine("    <AssemblyName>$AssemblyName</AssemblyName>")
    [void]$sb.AppendLine('    <TargetFramework>netstandard2.1</TargetFramework>')
    [void]$sb.AppendLine('    <BaseDirectory>.</BaseDirectory>')
    [void]$sb.AppendLine("    <DefineConstants>$defineConstants</DefineConstants>")
    [void]$sb.AppendLine('  </PropertyGroup>')
    [void]$sb.AppendLine('  <PropertyGroup>')
    [void]$sb.AppendLine('    <NoStandardLibraries>true</NoStandardLibraries>')
    [void]$sb.AppendLine('    <NoStdLib>true</NoStdLib>')
    [void]$sb.AppendLine('    <NoConfig>true</NoConfig>')
    [void]$sb.AppendLine('    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>')
    [void]$sb.AppendLine('    <MSBuildWarningsAsMessages>MSB3277</MSBuildWarningsAsMessages>')
    [void]$sb.AppendLine('  </PropertyGroup>')
    [void]$sb.AppendLine('  <PropertyGroup>')
    [void]$sb.AppendLine("    <ProjectGuid>{$projectGuid}</ProjectGuid>")
    [void]$sb.AppendLine("    <UnityProjectType>$projectType</UnityProjectType>")
    [void]$sb.AppendLine('    <UnityBuildTarget>StandaloneWindows64:19</UnityBuildTarget>')
    [void]$sb.AppendLine('    <UnityVersion>6000.0.49f1</UnityVersion>')
    [void]$sb.AppendLine('  </PropertyGroup>')

    if ($Rsp.Sources.Count -gt 0) {
        [void]$sb.AppendLine('  <ItemGroup>')
        foreach ($source in $Rsp.Sources) {
            [void]$sb.AppendLine("    <Compile Include=`"$source`" />")
        }
        [void]$sb.AppendLine('  </ItemGroup>')
    }

    if ($Rsp.AdditionalFiles.Count -gt 0) {
        [void]$sb.AppendLine('  <ItemGroup>')
        foreach ($additionalFile in $Rsp.AdditionalFiles) {
            [void]$sb.AppendLine("    <AdditionalFiles Include=`"$additionalFile`" />")
        }
        [void]$sb.AppendLine('  </ItemGroup>')
    }

    if ($Rsp.Analyzers.Count -gt 0) {
        [void]$sb.AppendLine('  <ItemGroup>')
        foreach ($analyzer in $Rsp.Analyzers) {
            [void]$sb.AppendLine("    <Analyzer Include=`"$analyzer`" />")
        }
        [void]$sb.AppendLine('  </ItemGroup>')
    }

    if ($Rsp.References.Count -gt 0) {
        [void]$sb.AppendLine('  <ItemGroup>')
        foreach ($reference in $Rsp.References) {
            $name = [System.IO.Path]::GetFileNameWithoutExtension($reference)
            [void]$sb.AppendLine("    <Reference Include=`"$name`">")
            [void]$sb.AppendLine("      <HintPath>$reference</HintPath>")
            [void]$sb.AppendLine('      <Private>False</Private>')
            [void]$sb.AppendLine('    </Reference>')
        }
        [void]$sb.AppendLine('  </ItemGroup>')
    }

    if ($ProjectReferences.Count -gt 0) {
        [void]$sb.AppendLine('  <ItemGroup>')
        foreach ($projectRef in $ProjectReferences) {
            [void]$sb.AppendLine("    <ProjectReference Include=`"$projectRef`" />")
        }
        [void]$sb.AppendLine('  </ItemGroup>')
    }

    [void]$sb.AppendLine('  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />')
    [void]$sb.AppendLine('  <ItemGroup>')
    [void]$sb.AppendLine('    <Capability Remove="LaunchProfiles" />')
    [void]$sb.AppendLine('    <Capability Remove="SharedProjectReferences" />')
    [void]$sb.AppendLine('    <Capability Remove="ReferenceManagerSharedProjects" />')
    [void]$sb.AppendLine('    <Capability Remove="ReferenceManagerProjects" />')
    [void]$sb.AppendLine('    <Capability Remove="COMReferences" />')
    [void]$sb.AppendLine('    <Capability Remove="ReferenceManagerCOM" />')
    [void]$sb.AppendLine('    <Capability Remove="AssemblyReferences" />')
    [void]$sb.AppendLine('    <Capability Remove="ReferenceManagerAssemblies" />')
    [void]$sb.AppendLine('  </ItemGroup>')
    [void]$sb.AppendLine('</Project>')

    return [pscustomobject]@{
        Path = Join-Path $ProjectRoot "$AssemblyName.csproj"
        Guid = $projectGuid
        Content = $sb.ToString()
    }
}

$beeDir = Join-Path $ProjectRoot 'Library\Bee\artifacts\1900b0aE.dag'
$gameRspPath = Join-Path $beeDir 'Assembly-CSharp.rsp'
$editorRspPath = Join-Path $beeDir 'Assembly-CSharp-Editor.rsp'

if (-not (Test-Path $gameRspPath)) {
    throw "Missing $gameRspPath. Open the project in Unity and wait for compilation to finish."
}

$gameRsp = Parse-RspFile $gameRspPath
$editorRsp = if (Test-Path $editorRspPath) { Parse-RspFile $editorRspPath } else { $null }

$gameProject = New-UnityCsproj -AssemblyName 'Assembly-CSharp' -OutputPath 'Temp\Bin\Debug\Assembly-CSharp\' -Rsp $gameRsp
$projects = @($gameProject)

if ($editorRsp) {
    $editorProject = New-UnityCsproj -AssemblyName 'Assembly-CSharp-Editor' -OutputPath 'Temp\Bin\Debug\Assembly-CSharp-Editor\' -Rsp $editorRsp -ProjectReferences @('Assembly-CSharp.csproj')
    $projects += $editorProject
}

foreach ($project in $projects) {
    Set-Content -Path $project.Path -Value $project.Content -Encoding UTF8
    Write-Host "Wrote $($project.Path)"
}

$projectName = Split-Path $ProjectRoot -Leaf
$solutionPath = Join-Path $ProjectRoot "$projectName.sln"
$solutionGuid = 'FAE04EC0-301F-11D3-BF4B-00C04F79EFBC'

$sln = New-Object System.Text.StringBuilder
[void]$sln.AppendLine('')
[void]$sln.AppendLine('Microsoft Visual Studio Solution File, Format Version 12.00')
[void]$sln.AppendLine('# Visual Studio 15')
foreach ($project in $projects) {
    $relativePath = Split-Path $project.Path -Leaf
    [void]$sln.AppendLine("Project(`"{$solutionGuid}`") = `"$([System.IO.Path]::GetFileNameWithoutExtension($relativePath))`", `"$relativePath`", `"{$($project.Guid)}`"")
    [void]$sln.AppendLine('EndProject')
}
[void]$sln.AppendLine('Global')
[void]$sln.AppendLine('    GlobalSection(SolutionConfigurationPlatforms) = preSolution')
[void]$sln.AppendLine('        Debug|Any CPU = Debug|Any CPU')
[void]$sln.AppendLine('        Release|Any CPU = Release|Any CPU')
[void]$sln.AppendLine('    EndGlobalSection')
[void]$sln.AppendLine('    GlobalSection(ProjectConfigurationPlatforms) = postSolution')
foreach ($project in $projects) {
    [void]$sln.AppendLine("        {$($project.Guid)}.Debug|Any CPU.ActiveCfg = Debug|Any CPU")
    [void]$sln.AppendLine("        {$($project.Guid)}.Debug|Any CPU.Build.0 = Debug|Any CPU")
    [void]$sln.AppendLine("        {$($project.Guid)}.Release|Any CPU.ActiveCfg = Release|Any CPU")
    [void]$sln.AppendLine("        {$($project.Guid)}.Release|Any CPU.Build.0 = Release|Any CPU")
}
[void]$sln.AppendLine('    EndGlobalSection')
[void]$sln.AppendLine('    GlobalSection(SolutionProperties) = preSolution')
[void]$sln.AppendLine('        HideSolutionNode = FALSE')
[void]$sln.AppendLine('    EndGlobalSection')
[void]$sln.AppendLine('EndGlobal')

Set-Content -Path $solutionPath -Value $sln.ToString() -Encoding UTF8
Write-Host "Wrote $solutionPath"
